### ISSUE TITLE
Fix the crasher (see prefect notes)

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/tgfp-nfl#16]
https://app.prefect.cloud/account/895436c3-82e4-4254-8d9e-da6f7fa0b31a/workspace/a55cc3f4-1279-4b38-be30-210371e69700/flow-runs/flow-run/49303619-06c6-4d8e-b9d4-e6f9003060ec

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/prefect/engine.py", line 849, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/prefect/_internal/concurrency/calls.py", line 293, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/prefect/_internal/concurrency/calls.py", line 318, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scripts/update_game_score.py", line 32, in run_update_game
    done_updating = update_game(tgfp_nfl_game_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scripts/update_game_score.py", line 57, in update_game
    done_updating: bool = _update_scores(nfl_data_source, tgfp_game)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scripts/update_game_score.py", line 78, in _update_scores
    if tgfp_game.home_team_score != int(nfl_game.total_home_points) or \
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tgfp_nfl/tgfp_nfl.py", line 312, in total_home_points
    self.__set_home_away_favorite_teams_and_score()
  File "/usr/local/lib/python3.11/dist-packages/tgfp_nfl/tgfp_nfl.py", line 378, in __set_home_away_favorite_teams_and_score
    self._home_team = self._data_source.find_teams(team_id=teams[0]['uid'])[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tgfp_nfl/tgfp_nfl.py", line 181, in find_teams
    for team in self.teams():
                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tgfp_nfl/tgfp_nfl.py", line 137, in teams
    self._standings_source_data = self.__get_standings_source_data()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tgfp_nfl/tgfp_nfl.py", line 84, in __get_standings_source_data
    afc_standings: List = content['children'][0]['standings']['entries']
                          ~~~~~~~^^^^^^^^^^^^
KeyError: 'children'
```

**Comment by johnsturgeon** [comment]
I'm pretty sure this crash is the same one that happens if there is no prediction data.

I'm going to test rl quick and if it is, I'm going to get a fix going
